name: event_manager
description: Event Manager App (SQFLite + Provider)
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.4
  intl: ^0.18.1
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  cloud_firestore: ^6.0.3

flutter:
  uses-material-design: true
  # If you want to add assets, put them here. Example:
  # assets:
  #   - assets/images/event.png
