// File generated by FlutterFire CLI (cleaned). If you re-run the FlutterFire CLI
// it may regenerate this file. The web/windows values were filled from an
// earlier run. Keep these values private and replace them if needed.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkmka7cPF4CF122B7XL6wSfBHGQk12h7U',
    appId: '1:860993950777:web:44d6b91eead5a0f5c1a9e8',
    messagingSenderId: '860993950777',
    projectId: 'geminidemo-8a0f0',
    authDomain: 'geminidemo-8a0f0.firebaseapp.com',
    databaseURL: 'https://geminidemo-8a0f0-default-rtdb.firebaseio.com',
    storageBucket: 'geminidemo-8a0f0.firebasestorage.app',
    measurementId: 'G-JMJ5MKS0Z8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkmka7cPF4CF122B7XL6wSfBHGQk12h7U',
    appId: '1:860993950777:web:758fedc69226157ec1a9e8',
    messagingSenderId: '860993950777',
    projectId: 'geminidemo-8a0f0',
    authDomain: 'geminidemo-8a0f0.firebaseapp.com',
    storageBucket: 'geminidemo-8a0f0.firebasestorage.app',
    measurementId: 'G-SPC4JW9Z3E',
  );
}